Code.require_file("test/support/xdr_fixtures.ex")
Code.require_file("test/support/fixtures/horizon.ex")
Code.require_file("test/support/fixtures/xdr/accounts.ex")
Code.require_file("test/support/fixtures/xdr/transactions.ex")
Code.require_file("test/support/fixtures/xdr/transaction_envelope.ex")
Code.require_file("test/support/fixtures/xdr/liquidity_pools.ex")
Code.require_file("test/support/fixtures/xdr/claimable_balances.ex")
Code.require_file("test/support/fixtures/xdr/trustline.ex")
Code.require_file("test/support/fixtures/xdr.ex")

ExUnit.start()
